imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                databases:
                    sqlite: true
                cache:
                    directories:
                        - vendor
                        - var/cache
            steps:
                - checkout
                - setup_database
                - composer install --prefer-dist --no-interaction
                - cp .env.test .env
                - php bin/console doctrine:database:create --env=test
                - php bin/console doctrine:schema:update --force --env=test
                - php bin/console doctrine:fixtures:load --env=test --no-interaction
                - php bin/phpunit

    tests:
        override:
            - command: "composer phpunit"
              coverage:
                  file: "docs/coverage.clover"
                  format: "php-clover"